#删除数据库
DROP DATABASE IF EXISTS BLOGSYSTEM;

#创建数据库
CREATE DATABASE BLOGSYSTEM DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

#选择数据库
USE BLOGSYSTEM;

#创建用户信息表
CREATE TABLE UserInfo(
	name VARCHAR(10) PRIMARY KEY
);

#创建管理员表
CREATE TABLE Admin(
	name VARCHAR(10) PRIMARY KEY,
	password VARCHAR(20) NOT NULL
);

#创建博客表
CREATE TABLE Blog(
	blogId INT PRIMARY KEY AUTO_INCREMENT,
	blogText LONGTEXT NOT NULL,
	name VARCHAR(10) NOT NULL,
	date DATE NOT NULL,
	blogTitle varchar(100) NOT NULL
);